version: '3'

services:
  satelite-postgres:
    image: postgres:latest
    container_name: satelite-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: satelite
    networks:
      - satelite-network

networks:
  satelite-network:
    driver: bridge
